### ISSUE TITLE
Bug Report (unable to download files)

### ISSUE THREAD

**Issue by starchypotatocode** [aidanaden/canvas-sync#234]
panic: runtime error: index out of range [5] with length 0
goroutine 143 [running]:te
github.com/aidanaden/canvas-sync/internal/pkg/canvas.(*CanvasClient).RecursiveUpdateNode.func3(0x5)
        /home/runner/work/canvas-sync/canvas-sync/internal/pkg/canvas/client.go:346 +0x16f
created by github.com/aidanaden/canvas-sync/internal/pkg/canvas.(*CanvasClient).RecursiveUpdateNode in goroutine 135
        /home/runner/work/canvas-sync/canvas-sync/internal/pkg/canvas/client.go:343 +0x45f

Checking the canvas webpage, the files that are there appear to be .sql amongst >10 other files, could that be the cause of the problem?

**Comment by webbrain-one** [comment]
Thanks for the detailed report! I’ve opened a pull request to address this: #236. It fixes the `index out of range` panic that was occurring in the recursive update logic, which can be triggered when processing certain file structures or directory contents. The fix adds a proper bounds check to prevent the crash. Please give it a try and let me know if it resolves the issue for you!
